### ISSUE TITLE
[ext] Add form information to Namibia response points on dashboard map

### ISSUE THREAD

**Issue by TNgidi** [locational/douma-app#456]
@onlyjsmith commented on [Mon Jul 16 2018](https://github.com/locational/_tickets/issues/279)

_External feedback source:_ https://github.com/disarm-platform/user-requests-and-feedback/issues/85
When user clicks on a response point they should be able to see the following information:

1. Date form was recorded
2. Village name
3. Head of household name
4. Household health number

---

@onlyjsmith commented on [Thu Jul 19 2018](https://github.com/locational/_tickets/issues/279#issuecomment-406211121)

@TNgidi can you try to figure out exactly what are the field names for each of these from the `form`?

**Comment by Nicolaidavies** [comment]
Deployed to stage.

**Comment by onlyjsmith** [comment]
Does this require any code? Just checking you mean "config updated on stage"?

**Comment by TNgidi** [comment]
@Nicolaidavies Is it possible to make the village information not pop when a response point is clicked?
![DiSARM Namibia IRS Tool 2018-07-26 09-00-18.png](https://images.zenhubusercontent.com/5ae1e96d4b5806bc2bd0c510/14a2256b-d4da-4776-9a15-cf9a4453c949)

**Comment by Nicolaidavies** [comment]
@onlyjsmith No code, just config.

**Comment by Nicolaidavies** [comment]
@TNgidi Not really. You can hide the village layer by selecting "show areas by:  No layer". Then you don't have two popups. 

The problem is when showing both the villages and responses, we cannot tell which layer you're interested in. So we show both popups.

**Comment by onlyjsmith** [comment]
I can’t remember exactly how we implemented (and I vaguely recall trying this before), but there’s definitely an order in which the layers are rendered, so we should be able to tell which layer is on top?

**Comment by onlyjsmith** [comment]
Think problem is we have two independent handlers: `_responses_click_handler` and a regular `_click_handler`. They both fire. We should combine their functionality.

So let’s not do this now! @tngidi can you add a new issue for this ‘duplicate pop-up on click’ issue? (Might be worth searching existing issues in douma and _tickets first)

**Comment by onlyjsmith** [comment]
Think problem is we have two independent handlers: `_responses_click_handler` and a regular `_click_handler`. They both fire. We should combine their functionality.

So let’s not do this now! @tngidi can you add a new issue for this ‘duplicate pop-up on click’ issue? (Might be worth searching existing issues in douma and _tickets first)

**Comment by TNgidi** [comment]
Ok, @onlyjsmith should this issue be here in the douma-app board or tickets

**Comment by onlyjsmith** [comment]
Can be in _tickets - thanks.

**Comment by TNgidi** [comment]
Done
