### ISSUE TITLE
[ext] NAM form transformation

### ISSUE THREAD

**Issue by onlyjsmith** [locational/douma-app#458]
@onlyjsmith commented on [Thu Jul 19 2018](https://github.com/locational/_tickets/issues/280)

_External feedback source:_ https://github.com/disarm-platform/user-requests-and-feedback/issues/86

[DiSARM Form Design_Iitula and Joyce.xlsx](https://github.com/disarm-platform/user-requests-and-feedback/files/2210373/DiSARM.Form.Design_Iitula.and.Joyce.xlsx)
[Namibia Form Flow.pptx](https://github.com/disarm-platform/user-requests-and-feedback/files/2210374/Namibia.Form.Flow.pptx)

**Comment by TNgidi** [comment]
NAM form Code found on this gist [here](https://gist.github.com/TNgidi/932eaa68226a6cc5389b5ab5a3b4af6e)
NAM form validations found on this gist [here](https://gist.github.com/TNgidi/862e9ec15591f7f70e68deef02985b77)

**Comment by TNgidi** [comment]
@Nicolaidavies I started building it then sent it to Sameen and she did some work, sent it back. from my tests it works well, is it a good form for you?

**Comment by Nicolaidavies** [comment]
This has been changed and deployed to staging.

**Comment by TNgidi** [comment]
Completed
