### ISSUE TITLE
[ext] Nam dashboard - removed red 'unsprayed' bar from stacked bar chart on the dashboard

### ISSUE THREAD

**Issue by TNgidi** [locational/douma-app#460]
@onlyjsmith commented on [Thu Jul 19 2018](https://github.com/locational/_tickets/issues/282)

_External feedback source:_ https://github.com/disarm-platform/user-requests-and-feedback/issues/89
Since we are not subtracting First visit unsprayed - Mop-up unsprayed this number will be inflated - we can just keep the cumulative green bar (# sprayed) and remove the red bar

**Comment by Nicolaidavies** [comment]
Has been deployed to stage.

**Comment by TNgidi** [comment]
Done
