### ISSUE TITLE
[ext] Namibia Record Filtering

### ISSUE THREAD

**Issue by TNgidi** [locational/douma-app#465]
@onlyjsmith commented on [Tue Jul 24 2018](https://github.com/locational/_tickets/issues/285)

_External feedback source:_ https://github.com/disarm-platform/user-requests-and-feedback/issues/90
@onlyjsmith @TNgidi Namibia has opted to use Head of Household Name as the filterable search field on the Record home page - we can go ahead and make this change

**Comment by TNgidi** [comment]
Deployed on staging with head of household name and location. @onlyjsmith is it okay to keep the location even if they asked only for the head of household name?

**Comment by onlyjsmith** [comment]
Yes - don't think there's an easy way to disable.

**Comment by TNgidi** [comment]
Done
