### ISSUE TITLE
[ext] Move response points map layer to top

### ISSUE THREAD

**Issue by onlyjsmith** [locational/douma-app#466]
@onlyjsmith commented on [Thu Jul 26 2018](https://github.com/locational/_tickets/issues/288)

_External feedback source:_ https://github.com/disarm-platform/user-requests-and-feedback/issues/91
@onlyjsmith @TNgidi 

Hi friends - Hoping this is a quick one - right now the map layers appear over the response points - can we make it so the response points are on top? Noticed this in all staging/prod instance...not sure when this got flipped

![image](https://user-images.githubusercontent.com/37877007/43258355-cc522ba4-90d2-11e8-9d4b-7ab9f1a713c9.png)

**Comment by TNgidi** [comment]
Done
