### ISSUE TITLE
Add risk to NAM villages geodata 

### ISSUE THREAD

**Issue by Nicolaidavies** [locational/douma-app#478]
We updated the NAM villages for 2018, but are missing risk.

Probably needs @HughSt.

**Comment by Nicolaidavies** [comment]
@HughSt Could you extract risk onto this geojson? 
[nam.villages.geojson.zip](https://github.com/locational/douma-app/files/2262737/nam_vlg_2018_multi_targeted.1.zip)

**Comment by onlyjsmith** [comment]
Think we’ve used ‘max’ risk in the past. Needs to be into a field just called `risk`.

Can you then paste the file back onto this issue? (think you need to zip geojson for Github to accept it)

**Comment by HughSt** [comment]
Working on it

**Comment by onlyjsmith** [comment]
Great! Thanks - I was starting to reinstall QGIS, but going in circles installing python2, uninstall python2, etc….

**Comment by HughSt** [comment]
Here you go. There is 1 village which has no risk as it lies outside Namibia and the risk map. Bloody thing was coded as -Inf by R which was making my life fun..Let me know if there are any issues.
[nam.villages.geojson.zip](https://github.com/locational/douma-app/files/2263769/nam.villages.geojson.zip)
![screen shot 2018-08-06 at 12 08 39 pm 1](https://user-images.githubusercontent.com/9344526/43736244-c6e2cbfe-9971-11e8-941e-ec5168551af1.png)

**Comment by onlyjsmith** [comment]
Awesome - thanks @HughSt. Think @Nicolaidavies was able to update the geodata and deploy to staging. Waiting for go-ahead from Sameen to deploy to prod.

**Comment by TNgidi** [comment]
Ready to close, linked to #464
