### ISSUE TITLE
[plan] with multipolygons can we select a village that spans multiple constituencies

### ISSUE THREAD

**Issue by onlyjsmith** [locational/douma-app#480]
There is likely to be a bug here

**Comment by onlyjsmith** [comment]
Can @TNgidi take a look at this tomorrow, see if he can find an example of this? There were some bugs on this last year which might point us in the right direction. If we’re having trouble finding examples, Sameen might be able to help finding villages to test with, but let’s first try ourselves.

**Comment by TNgidi** [comment]
@onlyjsmith I cannot see issues from last year on this board. It dates back only to February and from these I could not find one similar to this one. 

The error that I have seen is that I did not manage to close the polygon. 
https://www.useloom.com/share/71304b35e61148af9e27075dfa836635

I was going to test test with Kabbe north and Kabbe South, they seem to share some villages (Namyundu, Lubula A and Lusese)

**Comment by onlyjsmith** [comment]
@TNgidi just want to check - you think this is not reproducible, so we can close?

**Comment by onlyjsmith** [comment]
SOunds fixed
